Team26_ ex.3
SashaMogilevskii/RecSyS_MTS pull request #3
Opened 2022-12-04 18:19 UTC by SashaMogilevskii

- Предоставьте ноутбук(и) с экспериментами - написали свои ноутбуки ( ноутбук для моделей по топ к рекомендаций и модель для кнн). Ксения написала дополнительно dvc обертку моделей. 
- Сделали модели для предсказаний по KNN( тестили на 20, 30, 50 юзерах). Также делали блендинги моделей. 
- Решили вопрос с холодными юзерами и кол-вом рекомендаций меньшим чем K 
- Обернули модельки в сервис ( На сервис модель выгружается с дампа, и там крутится). Нюанс, в гит не получилось запушить модельку, так как весят дампы > 350мб. ( Если критично, можем загрузить дампы на гугл диск и оттуда выгружать, но не видели особой надобности, дампы храним локально. 
![image](https://user-images.githubusercontent.com/64280627/205508342-355ac51e-fbd9-4f9f-8aa1-ea6435165def.png)

2022-12-10 22:39 UTC, sharthZ23 requested changes

2022-12-10 22:39 UTC, sharthZ23 commented on service/modelss/allmodels.py
> +        reco = [9728, 13865, 15297, 10440, 3734, 4151, 142, 8636, 7571, 4495]
Читайте из файла эту информацию. Управляйте сервисом через конфиг, а не через апдейт кода

2022-12-10 22:39 UTC, sharthZ23 commented on service/modelss/allmodels.py
> +        self.list_top_items = np.array(
Читайте из файла эту информацию. Управляйте сервисом через конфиг, а не через апдейт кода

2022-12-10 22:39 UTC, sharthZ23 commented on service/modelss/allmodels.py
> +        self.model = jb.load("models/model_20.clf")
Покажите в ipynb, как вы эту модель/файл получили

2022-12-10 22:39 UTC, sharthZ23 commented on service/modelss/allmodels.py
> +        self.model = jb.load("models/model_20_all.clf")
Покажите в ipynb, как вы эту модель/файл получили

2022-12-11 15:04 UTC, SashaMogilevskii commented on service/modelss/allmodels.py
> +        self.list_top_items = np.array(
Добавил json

2022-12-11 15:04 UTC, SashaMogilevskii commented on service/modelss/allmodels.py
> +        reco = [9728, 13865, 15297, 10440, 3734, 4151, 142, 8636, 7571, 4495]
Добавил json

2022-12-11 16:28 UTC, XenaN commented on service/modelss/allmodels.py
> +        self.model = jb.load("models/model_20.clf")
Обучение выбранной модели было в скриптах, но потом мы узнали, что это не обязательно и убрали. Правда в ноутбук забыли добавить. Сейчас добавлено

2022-12-11 16:28 UTC, XenaN commented on service/modelss/allmodels.py
> +        self.model = jb.load("models/model_20_all.clf")
А это повтор той модели, экспериментировали с  размером датасета. Вообще ее уберем, ничего нам не дало.

2022-12-12 10:55 UTC, sharthZ23 approved these changes
Все ок, 25 баллов

2022-12-12 12:26 UTC, merged